version: '3.8'

services:
#  app:
#    container_name: elite-sas
#    restart: on-failure
#    build: ./app
#    network_mode: host
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
  database:
    image: 'postgres:alpine'
    container_name: elite-sas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "elite"
      POSTGRES_PASSWORD: "3l1t3"
      POSTGRES_DB: "elite-sas"
    ports:
      - "5424:5432"