// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package elite.sas.api.grpc;

public final class CommonsProto {
  private CommonsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code TenantType}
   */
  public enum TenantType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SCHOOL = 0;</code>
     */
    SCHOOL(0),
    /**
     * <code>COMPANY = 1;</code>
     */
    COMPANY(1),
    /**
     * <code>INTERNAL = 2;</code>
     */
    INTERNAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SCHOOL = 0;</code>
     */
    public static final int SCHOOL_VALUE = 0;
    /**
     * <code>COMPANY = 1;</code>
     */
    public static final int COMPANY_VALUE = 1;
    /**
     * <code>INTERNAL = 2;</code>
     */
    public static final int INTERNAL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TenantType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TenantType forNumber(int value) {
      switch (value) {
        case 0: return SCHOOL;
        case 1: return COMPANY;
        case 2: return INTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TenantType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TenantType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TenantType>() {
            public TenantType findValueByNumber(int number) {
              return TenantType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final TenantType[] VALUES = values();

    public static TenantType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TenantType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TenantType)
  }

  /**
   * Protobuf enum {@code UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STUDENT = 0;</code>
     */
    STUDENT(0),
    /**
     * <code>SUPERVISOR = 1;</code>
     */
    SUPERVISOR(1),
    /**
     * <code>ADMIN = 2;</code>
     */
    ADMIN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STUDENT = 0;</code>
     */
    public static final int STUDENT_VALUE = 0;
    /**
     * <code>SUPERVISOR = 1;</code>
     */
    public static final int SUPERVISOR_VALUE = 1;
    /**
     * <code>ADMIN = 2;</code>
     */
    public static final int ADMIN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserType forNumber(int value) {
      switch (value) {
        case 0: return STUDENT;
        case 1: return SUPERVISOR;
        case 2: return ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserType)
  }

  /**
   * Protobuf enum {@code RoleName}
   */
  public enum RoleName
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>student = 0;</code>
     */
    student(0),
    /**
     * <code>supervisor = 1;</code>
     */
    supervisor(1),
    /**
     * <code>TENANT_ADMIN = 2;</code>
     */
    TENANT_ADMIN(2),
    /**
     * <code>INTERNAL_ADMIN = 3;</code>
     */
    INTERNAL_ADMIN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>student = 0;</code>
     */
    public static final int student_VALUE = 0;
    /**
     * <code>supervisor = 1;</code>
     */
    public static final int supervisor_VALUE = 1;
    /**
     * <code>TENANT_ADMIN = 2;</code>
     */
    public static final int TENANT_ADMIN_VALUE = 2;
    /**
     * <code>INTERNAL_ADMIN = 3;</code>
     */
    public static final int INTERNAL_ADMIN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RoleName valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RoleName forNumber(int value) {
      switch (value) {
        case 0: return student;
        case 1: return supervisor;
        case 2: return TENANT_ADMIN;
        case 3: return INTERNAL_ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoleName> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleName>() {
            public RoleName findValueByNumber(int number) {
              return RoleName.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final RoleName[] VALUES = values();

    public static RoleName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RoleName(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RoleName)
  }

  /**
   * Protobuf enum {@code ApplicationStatus}
   */
  public enum ApplicationStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PENDING = 0;</code>
     */
    PENDING(0),
    /**
     * <code>ACCEPTED = 1;</code>
     */
    ACCEPTED(1),
    /**
     * <code>REJECTED = 2;</code>
     */
    REJECTED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PENDING = 0;</code>
     */
    public static final int PENDING_VALUE = 0;
    /**
     * <code>ACCEPTED = 1;</code>
     */
    public static final int ACCEPTED_VALUE = 1;
    /**
     * <code>REJECTED = 2;</code>
     */
    public static final int REJECTED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ApplicationStatus forNumber(int value) {
      switch (value) {
        case 0: return PENDING;
        case 1: return ACCEPTED;
        case 2: return REJECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>() {
            public ApplicationStatus findValueByNumber(int number) {
              return ApplicationStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(3);
    }

    private static final ApplicationStatus[] VALUES = values();

    public static ApplicationStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ApplicationStatus)
  }

  /**
   * Protobuf enum {@code AttachmentPeriod}
   */
  public enum AttachmentPeriod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JAN_MAR = 0;</code>
     */
    JAN_MAR(0),
    /**
     * <code>FEB_APR = 1;</code>
     */
    FEB_APR(1),
    /**
     * <code>MAR_MAY = 2;</code>
     */
    MAR_MAY(2),
    /**
     * <code>APR_JUN = 3;</code>
     */
    APR_JUN(3),
    /**
     * <code>MAY_JUL = 4;</code>
     */
    MAY_JUL(4),
    /**
     * <code>JUN_AUG = 5;</code>
     */
    JUN_AUG(5),
    /**
     * <code>JUL_SEP = 6;</code>
     */
    JUL_SEP(6),
    /**
     * <code>AUG_OCT = 7;</code>
     */
    AUG_OCT(7),
    /**
     * <code>SEP_NOV = 8;</code>
     */
    SEP_NOV(8),
    /**
     * <code>OCT_DEC = 9;</code>
     */
    OCT_DEC(9),
    /**
     * <code>NOV_JAN = 10;</code>
     */
    NOV_JAN(10),
    /**
     * <code>DEC_FEB = 11;</code>
     */
    DEC_FEB(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>JAN_MAR = 0;</code>
     */
    public static final int JAN_MAR_VALUE = 0;
    /**
     * <code>FEB_APR = 1;</code>
     */
    public static final int FEB_APR_VALUE = 1;
    /**
     * <code>MAR_MAY = 2;</code>
     */
    public static final int MAR_MAY_VALUE = 2;
    /**
     * <code>APR_JUN = 3;</code>
     */
    public static final int APR_JUN_VALUE = 3;
    /**
     * <code>MAY_JUL = 4;</code>
     */
    public static final int MAY_JUL_VALUE = 4;
    /**
     * <code>JUN_AUG = 5;</code>
     */
    public static final int JUN_AUG_VALUE = 5;
    /**
     * <code>JUL_SEP = 6;</code>
     */
    public static final int JUL_SEP_VALUE = 6;
    /**
     * <code>AUG_OCT = 7;</code>
     */
    public static final int AUG_OCT_VALUE = 7;
    /**
     * <code>SEP_NOV = 8;</code>
     */
    public static final int SEP_NOV_VALUE = 8;
    /**
     * <code>OCT_DEC = 9;</code>
     */
    public static final int OCT_DEC_VALUE = 9;
    /**
     * <code>NOV_JAN = 10;</code>
     */
    public static final int NOV_JAN_VALUE = 10;
    /**
     * <code>DEC_FEB = 11;</code>
     */
    public static final int DEC_FEB_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AttachmentPeriod valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AttachmentPeriod forNumber(int value) {
      switch (value) {
        case 0: return JAN_MAR;
        case 1: return FEB_APR;
        case 2: return MAR_MAY;
        case 3: return APR_JUN;
        case 4: return MAY_JUL;
        case 5: return JUN_AUG;
        case 6: return JUL_SEP;
        case 7: return AUG_OCT;
        case 8: return SEP_NOV;
        case 9: return OCT_DEC;
        case 10: return NOV_JAN;
        case 11: return DEC_FEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AttachmentPeriod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AttachmentPeriod> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AttachmentPeriod>() {
            public AttachmentPeriod findValueByNumber(int number) {
              return AttachmentPeriod.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(4);
    }

    private static final AttachmentPeriod[] VALUES = values();

    public static AttachmentPeriod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AttachmentPeriod(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AttachmentPeriod)
  }

  /**
   * Protobuf enum {@code CourseLevel}
   */
  public enum CourseLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIPLOMA = 0;</code>
     */
    DIPLOMA(0),
    /**
     * <code>CERTIFICATE = 1;</code>
     */
    CERTIFICATE(1),
    /**
     * <code>DEGREE = 2;</code>
     */
    DEGREE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DIPLOMA = 0;</code>
     */
    public static final int DIPLOMA_VALUE = 0;
    /**
     * <code>CERTIFICATE = 1;</code>
     */
    public static final int CERTIFICATE_VALUE = 1;
    /**
     * <code>DEGREE = 2;</code>
     */
    public static final int DEGREE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CourseLevel valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CourseLevel forNumber(int value) {
      switch (value) {
        case 0: return DIPLOMA;
        case 1: return CERTIFICATE;
        case 2: return DEGREE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CourseLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CourseLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CourseLevel>() {
            public CourseLevel findValueByNumber(int number) {
              return CourseLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(5);
    }

    private static final CourseLevel[] VALUES = values();

    public static CourseLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CourseLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CourseLevel)
  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              elite.sas.api.grpc.CommonsProto.Empty.class, elite.sas.api.grpc.CommonsProto.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof elite.sas.api.grpc.CommonsProto.Empty)) {
        return super.equals(obj);
      }
      elite.sas.api.grpc.CommonsProto.Empty other = (elite.sas.api.grpc.CommonsProto.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(elite.sas.api.grpc.CommonsProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        elite.sas.api.grpc.CommonsProto.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                elite.sas.api.grpc.CommonsProto.Empty.class, elite.sas.api.grpc.CommonsProto.Empty.Builder.class);
      }

      // Construct using elite.sas.api.grpc.CommonsProto.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty getDefaultInstanceForType() {
        return elite.sas.api.grpc.CommonsProto.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty build() {
        elite.sas.api.grpc.CommonsProto.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty buildPartial() {
        elite.sas.api.grpc.CommonsProto.Empty result = new elite.sas.api.grpc.CommonsProto.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof elite.sas.api.grpc.CommonsProto.Empty) {
          return mergeFrom((elite.sas.api.grpc.CommonsProto.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(elite.sas.api.grpc.CommonsProto.Empty other) {
        if (other == elite.sas.api.grpc.CommonsProto.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        elite.sas.api.grpc.CommonsProto.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (elite.sas.api.grpc.CommonsProto.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final elite.sas.api.grpc.CommonsProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new elite.sas.api.grpc.CommonsProto.Empty();
    }

    public static elite.sas.api.grpc.CommonsProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public elite.sas.api.grpc.CommonsProto.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommons.proto\"\007\n\005Empty*3\n\nTenantType\022\n" +
      "\n\006SCHOOL\020\000\022\013\n\007COMPANY\020\001\022\014\n\010INTERNAL\020\002*2\n" +
      "\010UserType\022\013\n\007STUDENT\020\000\022\016\n\nSUPERVISOR\020\001\022\t" +
      "\n\005ADMIN\020\002*M\n\010RoleName\022\013\n\007student\020\000\022\016\n\nsu" +
      "pervisor\020\001\022\020\n\014TENANT_ADMIN\020\002\022\022\n\016INTERNAL" +
      "_ADMIN\020\003*<\n\021ApplicationStatus\022\013\n\007PENDING" +
      "\020\000\022\014\n\010ACCEPTED\020\001\022\014\n\010REJECTED\020\002*\256\001\n\020Attac" +
      "hmentPeriod\022\013\n\007JAN_MAR\020\000\022\013\n\007FEB_APR\020\001\022\013\n" +
      "\007MAR_MAY\020\002\022\013\n\007APR_JUN\020\003\022\013\n\007MAY_JUL\020\004\022\013\n\007" +
      "JUN_AUG\020\005\022\013\n\007JUL_SEP\020\006\022\013\n\007AUG_OCT\020\007\022\013\n\007S" +
      "EP_NOV\020\010\022\013\n\007OCT_DEC\020\t\022\013\n\007NOV_JAN\020\n\022\013\n\007DE" +
      "C_FEB\020\013*7\n\013CourseLevel\022\013\n\007DIPLOMA\020\000\022\017\n\013C" +
      "ERTIFICATE\020\001\022\n\n\006DEGREE\020\002B$\n\022elite.sas.ap" +
      "i.grpcB\014CommonsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
