// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package elite.sas.api.grpc;

public final class CommonsProto {
  private CommonsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code TenantType}
   */
  public enum TenantType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SCHOOL = 0;</code>
     */
    SCHOOL(0),
    /**
     * <code>COMPANY = 1;</code>
     */
    COMPANY(1),
    /**
     * <code>INTERNAL = 2;</code>
     */
    INTERNAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SCHOOL = 0;</code>
     */
    public static final int SCHOOL_VALUE = 0;
    /**
     * <code>COMPANY = 1;</code>
     */
    public static final int COMPANY_VALUE = 1;
    /**
     * <code>INTERNAL = 2;</code>
     */
    public static final int INTERNAL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TenantType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TenantType forNumber(int value) {
      switch (value) {
        case 0: return SCHOOL;
        case 1: return COMPANY;
        case 2: return INTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TenantType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TenantType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TenantType>() {
            public TenantType findValueByNumber(int number) {
              return TenantType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final TenantType[] VALUES = values();

    public static TenantType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TenantType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TenantType)
  }

  /**
   * Protobuf enum {@code UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STUDENT = 0;</code>
     */
    STUDENT(0),
    /**
     * <code>SUPERVISOR = 1;</code>
     */
    SUPERVISOR(1),
    /**
     * <code>ADMIN = 2;</code>
     */
    ADMIN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STUDENT = 0;</code>
     */
    public static final int STUDENT_VALUE = 0;
    /**
     * <code>SUPERVISOR = 1;</code>
     */
    public static final int SUPERVISOR_VALUE = 1;
    /**
     * <code>ADMIN = 2;</code>
     */
    public static final int ADMIN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserType forNumber(int value) {
      switch (value) {
        case 0: return STUDENT;
        case 1: return SUPERVISOR;
        case 2: return ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserType)
  }

  /**
   * Protobuf enum {@code RoleName}
   */
  public enum RoleName
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>student = 0;</code>
     */
    student(0),
    /**
     * <code>supervisor = 1;</code>
     */
    supervisor(1),
    /**
     * <code>TENANT_ADMIN = 2;</code>
     */
    TENANT_ADMIN(2),
    /**
     * <code>INTERNAL_ADMIN = 3;</code>
     */
    INTERNAL_ADMIN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>student = 0;</code>
     */
    public static final int student_VALUE = 0;
    /**
     * <code>supervisor = 1;</code>
     */
    public static final int supervisor_VALUE = 1;
    /**
     * <code>TENANT_ADMIN = 2;</code>
     */
    public static final int TENANT_ADMIN_VALUE = 2;
    /**
     * <code>INTERNAL_ADMIN = 3;</code>
     */
    public static final int INTERNAL_ADMIN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RoleName valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RoleName forNumber(int value) {
      switch (value) {
        case 0: return student;
        case 1: return supervisor;
        case 2: return TENANT_ADMIN;
        case 3: return INTERNAL_ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoleName> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleName>() {
            public RoleName findValueByNumber(int number) {
              return RoleName.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final RoleName[] VALUES = values();

    public static RoleName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RoleName(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RoleName)
  }

  /**
   * Protobuf enum {@code ApplicationStatus}
   */
  public enum ApplicationStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PENDING = 0;</code>
     */
    PENDING(0),
    /**
     * <code>ACCEPTED = 1;</code>
     */
    ACCEPTED(1),
    /**
     * <code>REJECTED = 2;</code>
     */
    REJECTED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PENDING = 0;</code>
     */
    public static final int PENDING_VALUE = 0;
    /**
     * <code>ACCEPTED = 1;</code>
     */
    public static final int ACCEPTED_VALUE = 1;
    /**
     * <code>REJECTED = 2;</code>
     */
    public static final int REJECTED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ApplicationStatus forNumber(int value) {
      switch (value) {
        case 0: return PENDING;
        case 1: return ACCEPTED;
        case 2: return REJECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>() {
            public ApplicationStatus findValueByNumber(int number) {
              return ApplicationStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(3);
    }

    private static final ApplicationStatus[] VALUES = values();

    public static ApplicationStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ApplicationStatus)
  }

  /**
   * Protobuf enum {@code AttachmentPeriod}
   */
  public enum AttachmentPeriod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JAN_MAR = 0;</code>
     */
    JAN_MAR(0),
    /**
     * <code>FEB_APR = 1;</code>
     */
    FEB_APR(1),
    /**
     * <code>MAR_MAY = 2;</code>
     */
    MAR_MAY(2),
    /**
     * <code>APR_JUN = 3;</code>
     */
    APR_JUN(3),
    /**
     * <code>MAY_JUL = 4;</code>
     */
    MAY_JUL(4),
    /**
     * <code>JUN_AUG = 5;</code>
     */
    JUN_AUG(5),
    /**
     * <code>JUL_SEP = 6;</code>
     */
    JUL_SEP(6),
    /**
     * <code>AUG_OCT = 7;</code>
     */
    AUG_OCT(7),
    /**
     * <code>SEP_NOV = 8;</code>
     */
    SEP_NOV(8),
    /**
     * <code>OCT_DEC = 9;</code>
     */
    OCT_DEC(9),
    /**
     * <code>NOV_JAN = 10;</code>
     */
    NOV_JAN(10),
    /**
     * <code>DEC_FEB = 11;</code>
     */
    DEC_FEB(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>JAN_MAR = 0;</code>
     */
    public static final int JAN_MAR_VALUE = 0;
    /**
     * <code>FEB_APR = 1;</code>
     */
    public static final int FEB_APR_VALUE = 1;
    /**
     * <code>MAR_MAY = 2;</code>
     */
    public static final int MAR_MAY_VALUE = 2;
    /**
     * <code>APR_JUN = 3;</code>
     */
    public static final int APR_JUN_VALUE = 3;
    /**
     * <code>MAY_JUL = 4;</code>
     */
    public static final int MAY_JUL_VALUE = 4;
    /**
     * <code>JUN_AUG = 5;</code>
     */
    public static final int JUN_AUG_VALUE = 5;
    /**
     * <code>JUL_SEP = 6;</code>
     */
    public static final int JUL_SEP_VALUE = 6;
    /**
     * <code>AUG_OCT = 7;</code>
     */
    public static final int AUG_OCT_VALUE = 7;
    /**
     * <code>SEP_NOV = 8;</code>
     */
    public static final int SEP_NOV_VALUE = 8;
    /**
     * <code>OCT_DEC = 9;</code>
     */
    public static final int OCT_DEC_VALUE = 9;
    /**
     * <code>NOV_JAN = 10;</code>
     */
    public static final int NOV_JAN_VALUE = 10;
    /**
     * <code>DEC_FEB = 11;</code>
     */
    public static final int DEC_FEB_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AttachmentPeriod valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AttachmentPeriod forNumber(int value) {
      switch (value) {
        case 0: return JAN_MAR;
        case 1: return FEB_APR;
        case 2: return MAR_MAY;
        case 3: return APR_JUN;
        case 4: return MAY_JUL;
        case 5: return JUN_AUG;
        case 6: return JUL_SEP;
        case 7: return AUG_OCT;
        case 8: return SEP_NOV;
        case 9: return OCT_DEC;
        case 10: return NOV_JAN;
        case 11: return DEC_FEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AttachmentPeriod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AttachmentPeriod> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AttachmentPeriod>() {
            public AttachmentPeriod findValueByNumber(int number) {
              return AttachmentPeriod.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(4);
    }

    private static final AttachmentPeriod[] VALUES = values();

    public static AttachmentPeriod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AttachmentPeriod(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AttachmentPeriod)
  }

  /**
   * Protobuf enum {@code CourseLevel}
   */
  public enum CourseLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIPLOMA = 0;</code>
     */
    DIPLOMA(0),
    /**
     * <code>CERTIFICATE = 1;</code>
     */
    CERTIFICATE(1),
    /**
     * <code>DEGREE = 2;</code>
     */
    DEGREE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DIPLOMA = 0;</code>
     */
    public static final int DIPLOMA_VALUE = 0;
    /**
     * <code>CERTIFICATE = 1;</code>
     */
    public static final int CERTIFICATE_VALUE = 1;
    /**
     * <code>DEGREE = 2;</code>
     */
    public static final int DEGREE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CourseLevel valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CourseLevel forNumber(int value) {
      switch (value) {
        case 0: return DIPLOMA;
        case 1: return CERTIFICATE;
        case 2: return DEGREE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CourseLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CourseLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CourseLevel>() {
            public CourseLevel findValueByNumber(int number) {
              return CourseLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.getDescriptor().getEnumTypes().get(5);
    }

    private static final CourseLevel[] VALUES = values();

    public static CourseLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CourseLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CourseLevel)
  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              elite.sas.api.grpc.CommonsProto.Empty.class, elite.sas.api.grpc.CommonsProto.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof elite.sas.api.grpc.CommonsProto.Empty)) {
        return super.equals(obj);
      }
      elite.sas.api.grpc.CommonsProto.Empty other = (elite.sas.api.grpc.CommonsProto.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(elite.sas.api.grpc.CommonsProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        elite.sas.api.grpc.CommonsProto.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                elite.sas.api.grpc.CommonsProto.Empty.class, elite.sas.api.grpc.CommonsProto.Empty.Builder.class);
      }

      // Construct using elite.sas.api.grpc.CommonsProto.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty getDefaultInstanceForType() {
        return elite.sas.api.grpc.CommonsProto.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty build() {
        elite.sas.api.grpc.CommonsProto.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Empty buildPartial() {
        elite.sas.api.grpc.CommonsProto.Empty result = new elite.sas.api.grpc.CommonsProto.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof elite.sas.api.grpc.CommonsProto.Empty) {
          return mergeFrom((elite.sas.api.grpc.CommonsProto.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(elite.sas.api.grpc.CommonsProto.Empty other) {
        if (other == elite.sas.api.grpc.CommonsProto.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        elite.sas.api.grpc.CommonsProto.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (elite.sas.api.grpc.CommonsProto.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final elite.sas.api.grpc.CommonsProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new elite.sas.api.grpc.CommonsProto.Empty();
    }

    public static elite.sas.api.grpc.CommonsProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public elite.sas.api.grpc.CommonsProto.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     * @return The updatedAt.
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     * @return Whether the deletedAt field is set.
     */
    boolean hasDeletedAt();
    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     * @return The deletedAt.
     */
    com.google.protobuf.Timestamp getDeletedAt();
    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder();
  }
  /**
   * Protobuf type {@code Metadata}
   */
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Metadata)
      MetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Metadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createdAt_ != null) {
                subBuilder = createdAt_.toBuilder();
              }
              createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createdAt_);
                createdAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updatedAt_ != null) {
                subBuilder = updatedAt_.toBuilder();
              }
              updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updatedAt_);
                updatedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (deletedAt_ != null) {
                subBuilder = deletedAt_.toBuilder();
              }
              deletedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deletedAt_);
                deletedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Metadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return elite.sas.api.grpc.CommonsProto.internal_static_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              elite.sas.api.grpc.CommonsProto.Metadata.class, elite.sas.api.grpc.CommonsProto.Metadata.Builder.class);
    }

    public static final int CREATEDAT_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return getCreatedAt();
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     * @return Whether the updatedAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return getUpdatedAt();
    }

    public static final int DELETEDAT_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp deletedAt_;
    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     * @return Whether the deletedAt field is set.
     */
    @java.lang.Override
    public boolean hasDeletedAt() {
      return deletedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     * @return The deletedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDeletedAt() {
      return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
      return getDeletedAt();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (createdAt_ != null) {
        output.writeMessage(1, getCreatedAt());
      }
      if (updatedAt_ != null) {
        output.writeMessage(2, getUpdatedAt());
      }
      if (deletedAt_ != null) {
        output.writeMessage(3, getDeletedAt());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (createdAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCreatedAt());
      }
      if (updatedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUpdatedAt());
      }
      if (deletedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDeletedAt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof elite.sas.api.grpc.CommonsProto.Metadata)) {
        return super.equals(obj);
      }
      elite.sas.api.grpc.CommonsProto.Metadata other = (elite.sas.api.grpc.CommonsProto.Metadata) obj;

      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (hasDeletedAt() != other.hasDeletedAt()) return false;
      if (hasDeletedAt()) {
        if (!getDeletedAt()
            .equals(other.getDeletedAt())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      if (hasDeletedAt()) {
        hash = (37 * hash) + DELETEDAT_FIELD_NUMBER;
        hash = (53 * hash) + getDeletedAt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static elite.sas.api.grpc.CommonsProto.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(elite.sas.api.grpc.CommonsProto.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Metadata)
        elite.sas.api.grpc.CommonsProto.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Metadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                elite.sas.api.grpc.CommonsProto.Metadata.class, elite.sas.api.grpc.CommonsProto.Metadata.Builder.class);
      }

      // Construct using elite.sas.api.grpc.CommonsProto.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (createdAtBuilder_ == null) {
          createdAt_ = null;
        } else {
          createdAt_ = null;
          createdAtBuilder_ = null;
        }
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }
        if (deletedAtBuilder_ == null) {
          deletedAt_ = null;
        } else {
          deletedAt_ = null;
          deletedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return elite.sas.api.grpc.CommonsProto.internal_static_Metadata_descriptor;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Metadata getDefaultInstanceForType() {
        return elite.sas.api.grpc.CommonsProto.Metadata.getDefaultInstance();
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Metadata build() {
        elite.sas.api.grpc.CommonsProto.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public elite.sas.api.grpc.CommonsProto.Metadata buildPartial() {
        elite.sas.api.grpc.CommonsProto.Metadata result = new elite.sas.api.grpc.CommonsProto.Metadata(this);
        if (createdAtBuilder_ == null) {
          result.createdAt_ = createdAt_;
        } else {
          result.createdAt_ = createdAtBuilder_.build();
        }
        if (updatedAtBuilder_ == null) {
          result.updatedAt_ = updatedAt_;
        } else {
          result.updatedAt_ = updatedAtBuilder_.build();
        }
        if (deletedAtBuilder_ == null) {
          result.deletedAt_ = deletedAt_;
        } else {
          result.deletedAt_ = deletedAtBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof elite.sas.api.grpc.CommonsProto.Metadata) {
          return mergeFrom((elite.sas.api.grpc.CommonsProto.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(elite.sas.api.grpc.CommonsProto.Metadata other) {
        if (other == elite.sas.api.grpc.CommonsProto.Metadata.getDefaultInstance()) return this;
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        if (other.hasDeletedAt()) {
          mergeDeletedAt(other.getDeletedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        elite.sas.api.grpc.CommonsProto.Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (elite.sas.api.grpc.CommonsProto.Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return createdAtBuilder_ != null || createdAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
          onChanged();
        } else {
          createdAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
          onChanged();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (createdAt_ != null) {
            createdAt_ =
              com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
          } else {
            createdAt_ = value;
          }
          onChanged();
        } else {
          createdAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public Builder clearCreatedAt() {
        if (createdAtBuilder_ == null) {
          createdAt_ = null;
          onChanged();
        } else {
          createdAt_ = null;
          createdAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.google.protobuf.Timestamp updatedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return updatedAtBuilder_ != null || updatedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       * @return The updatedAt.
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (updatedAt_ != null) {
            updatedAt_ =
              com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
          } else {
            updatedAt_ = value;
          }
          onChanged();
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public Builder clearUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
          onChanged();
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updatedAt = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      private com.google.protobuf.Timestamp deletedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       * @return Whether the deletedAt field is set.
       */
      public boolean hasDeletedAt() {
        return deletedAtBuilder_ != null || deletedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       * @return The deletedAt.
       */
      public com.google.protobuf.Timestamp getDeletedAt() {
        if (deletedAtBuilder_ == null) {
          return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
        } else {
          return deletedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public Builder setDeletedAt(com.google.protobuf.Timestamp value) {
        if (deletedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deletedAt_ = value;
          onChanged();
        } else {
          deletedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public Builder setDeletedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (deletedAtBuilder_ == null) {
          deletedAt_ = builderForValue.build();
          onChanged();
        } else {
          deletedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public Builder mergeDeletedAt(com.google.protobuf.Timestamp value) {
        if (deletedAtBuilder_ == null) {
          if (deletedAt_ != null) {
            deletedAt_ =
              com.google.protobuf.Timestamp.newBuilder(deletedAt_).mergeFrom(value).buildPartial();
          } else {
            deletedAt_ = value;
          }
          onChanged();
        } else {
          deletedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public Builder clearDeletedAt() {
        if (deletedAtBuilder_ == null) {
          deletedAt_ = null;
          onChanged();
        } else {
          deletedAt_ = null;
          deletedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDeletedAtBuilder() {
        
        onChanged();
        return getDeletedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
        if (deletedAtBuilder_ != null) {
          return deletedAtBuilder_.getMessageOrBuilder();
        } else {
          return deletedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp deletedAt = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDeletedAtFieldBuilder() {
        if (deletedAtBuilder_ == null) {
          deletedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDeletedAt(),
                  getParentForChildren(),
                  isClean());
          deletedAt_ = null;
        }
        return deletedAtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Metadata)
    }

    // @@protoc_insertion_point(class_scope:Metadata)
    private static final elite.sas.api.grpc.CommonsProto.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new elite.sas.api.grpc.CommonsProto.Metadata();
    }

    public static elite.sas.api.grpc.CommonsProto.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      @java.lang.Override
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public elite.sas.api.grpc.CommonsProto.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommons.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\007\n\005Empty\"\227\001\n\010Metadata\022-\n\tcreate" +
      "dAt\030\001 \001(\0132\032.google.protobuf.Timestamp\022-\n" +
      "\tupdatedAt\030\002 \001(\0132\032.google.protobuf.Times" +
      "tamp\022-\n\tdeletedAt\030\003 \001(\0132\032.google.protobu" +
      "f.Timestamp*3\n\nTenantType\022\n\n\006SCHOOL\020\000\022\013\n" +
      "\007COMPANY\020\001\022\014\n\010INTERNAL\020\002*2\n\010UserType\022\013\n\007" +
      "STUDENT\020\000\022\016\n\nSUPERVISOR\020\001\022\t\n\005ADMIN\020\002*M\n\010" +
      "RoleName\022\013\n\007student\020\000\022\016\n\nsupervisor\020\001\022\020\n" +
      "\014TENANT_ADMIN\020\002\022\022\n\016INTERNAL_ADMIN\020\003*<\n\021A" +
      "pplicationStatus\022\013\n\007PENDING\020\000\022\014\n\010ACCEPTE" +
      "D\020\001\022\014\n\010REJECTED\020\002*\256\001\n\020AttachmentPeriod\022\013" +
      "\n\007JAN_MAR\020\000\022\013\n\007FEB_APR\020\001\022\013\n\007MAR_MAY\020\002\022\013\n" +
      "\007APR_JUN\020\003\022\013\n\007MAY_JUL\020\004\022\013\n\007JUN_AUG\020\005\022\013\n\007" +
      "JUL_SEP\020\006\022\013\n\007AUG_OCT\020\007\022\013\n\007SEP_NOV\020\010\022\013\n\007O" +
      "CT_DEC\020\t\022\013\n\007NOV_JAN\020\n\022\013\n\007DEC_FEB\020\013*7\n\013Co" +
      "urseLevel\022\013\n\007DIPLOMA\020\000\022\017\n\013CERTIFICATE\020\001\022" +
      "\n\n\006DEGREE\020\002B$\n\022elite.sas.api.grpcB\014Commo" +
      "nsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new java.lang.String[] { "CreatedAt", "UpdatedAt", "DeletedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
