name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: release docker image
      uses: actions/checkout@v3
      
    - name: Set up latest available JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Build with Gradle
      run: ./gradlew clean build

    
    - name: Build the Docker image
      run: docker build . --file app/Dockerfile --tag my-image-name:$(date +%s)
